export interface TalkingObject {
  id: string
  name: string
  emoji: string
  gancho: string        // frase de abertura do reel (usada no prompt Claude)
  personalidade: string // tom de voz do objeto
  prompt: string        // prompt de imagem para Fal.ai / Midjourney
}

export const TALKING_OBJECTS: Record<string, TalkingObject[]> = {
  imoveis: [
    {
      id: 'house_key',
      name: 'Chave de Casa',
      emoji: '🔑',
      gancho: 'Eu sou a chave que abre a porta do imóvel dos seus sonhos. Quer saber quanto vai custar?',
      personalidade: 'Reveladora, sedutora',
      prompt: 'A magical golden house key character with expressive friendly face, glowing eyes, floating in warm light, photorealistic 3D render, Pixar-like quality, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'sold_sign',
      name: 'Placa VENDIDO',
      emoji: '🏠',
      gancho: 'Fui colocada aqui hoje. Sabe quantos meses esse imóvel estava esperando pelo dono certo?',
      personalidade: 'Emocionante, impactante',
      prompt: 'An animated Brazilian VENDIDO real estate sign character with happy expressive face, bold red and white colors, 3D render, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'contract',
      name: 'Contrato',
      emoji: '📄',
      gancho: 'Tenho 47 cláusulas. A maioria assina sem ler a número 12. Isso pode custar caro.',
      personalidade: 'Sério, alerta',
      prompt: 'An animated official real estate contract character with reading glasses and trustworthy face, professional blue tones, 3D render, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'apartment_window',
      name: 'Janela com Vista',
      emoji: '🪟',
      gancho: 'Estou esperando o dono certo há 3 meses. Olha o que eu vejo todo dia daqui de cima.',
      personalidade: 'Misteriosa, sedutora',
      prompt: 'A beautiful apartment window character with warm welcoming face, ocean view through glass, golden hour lighting, 3D animated style, lip-sync ready, aspect ratio 9:16',
    },
    {
      id: 'house_robot',
      name: 'Robô Corretor',
      emoji: '🤖',
      gancho: 'Analisei 847 imóveis nessa região. Deixa eu te mostrar os 3 melhores custo-benefício.',
      personalidade: 'Especialista, tecnológico',
      prompt: 'A friendly real estate robot character in tiny blazer, holding miniature house, metallic silver with gold accents, Pixar-style 3D, expressive lip-sync face, aspect ratio 9:16',
    },
  ],

  beleza: [
    {
      id: 'scissors',
      name: 'Tesoura Mágica',
      emoji: '✂️',
      gancho: 'Já cortei mais de 10.000 cabelos. Mas o seu vai ser o mais especial. Deixa eu te contar por quê.',
      personalidade: 'Experiente, carismática',
      prompt: 'An animated magical hair scissors character with sparkly personality, rainbow sheen, expressive lip-sync face, salon background, 3D Pixar render, aspect ratio 9:16',
    },
    {
      id: 'mirror',
      name: 'Espelho da Beleza',
      emoji: '🪞',
      gancho: 'Todo dia você me olha e vê o mesmo. Hoje eu vou te mostrar quem você pode ser.',
      personalidade: 'Revelador, motivacional',
      prompt: 'A glamorous vanity mirror character, ornate gold frame, flirty expressive face, beauty salon, 3D Pixar style, lip-sync ready, aspect ratio 9:16',
    },
    {
      id: 'hair_brush',
      name: 'Escova Profissional',
      emoji: '💇',
      gancho: 'Sabe a diferença entre uma escova de R$30 e uma de R$300? Eu sei. E vou te contar.',
      personalidade: 'Especialista, direta',
      prompt: 'A professional hair brush character with wavy hair flowing, warm friendly face, salon context, 3D render, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'nail_polish',
      name: 'Esmalte Animado',
      emoji: '💅',
      gancho: 'Tenho 348 cores. Mas só 5 são as que realmente duram 3 semanas. Quer saber quais?',
      personalidade: 'Especialista, reveladora',
      prompt: 'An animated nail polish bottle character, glamorous sparkly personality, expressive face, beauty context, 3D Pixar render, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'hair_dryer',
      name: 'Secador Falante',
      emoji: '💨',
      gancho: 'A temperatura errada destruiu mais cabelos do que você imagina. Vou te ensinar o jeito certo.',
      personalidade: 'Professora, cuidadosa',
      prompt: 'A friendly hair dryer character blowing colorful wind, expressive animated face, salon environment, 3D render, lip-sync ready, aspect ratio 9:16',
    },
  ],

  saude: [
    {
      id: 'stethoscope',
      name: 'Estetoscópio',
      emoji: '🩺',
      gancho: 'Já ouvi mais de 5.000 corações. O seu está me pedindo atenção. Você está ouvindo?',
      personalidade: 'Cuidadoso, empático',
      prompt: 'An animated medical stethoscope character with caring face, doctor look, clinical environment, 3D render, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'medical_chart',
      name: 'Prontuário',
      emoji: '📊',
      gancho: 'Tenho todos os seus resultados. Mas você só me lê quando a situação já ficou grave.',
      personalidade: 'Sério, alerta',
      prompt: 'An animated medical chart clipboard character, reading glasses, helpful expression, 3D medical aesthetic, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'tooth',
      name: 'Dente Feliz',
      emoji: '🦷',
      gancho: 'Fui escovado 3x ao dia por 30 anos. Ainda assim precisei de canal. Sabe por quê?',
      personalidade: 'Educativo, irônico',
      prompt: 'A cheerful animated tooth character with wide smile, clean white, dental clinic background, 3D Pixar style, lip-sync ready, aspect ratio 9:16',
    },
    {
      id: 'pill',
      name: 'Cápsula Saudável',
      emoji: '💊',
      gancho: 'Sou tomada todo dia. Mas sem acompanhamento médico, posso fazer mais mal do que bem.',
      personalidade: 'Especialista, responsável',
      prompt: 'A friendly medicine capsule character half red half white, health-focused, clean background, 3D animated, expressive lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'heart',
      name: 'Coração Animado',
      emoji: '❤️',
      gancho: 'Bato 100.000 vezes por dia sem parar. Você cuida de mim como eu cuido de você?',
      personalidade: 'Emocional, motivacional',
      prompt: 'An animated healthy heart character, energetic personality, red with golden highlights, fitness context, 3D Pixar style, lip-sync face, aspect ratio 9:16',
    },
  ],

  juridico: [
    {
      id: 'law_book',
      name: 'Livro de Leis',
      emoji: '⚖️',
      gancho: 'Tenho 847 artigos. O que está te prejudicando está no artigo 927. Você conhece seus direitos?',
      personalidade: 'Especialista, direto',
      prompt: 'An animated law book in burgundy leather, golden scales, wise authoritative face, 3D render, lip-sync mouth, legal setting, aspect ratio 9:16',
    },
    {
      id: 'gavel',
      name: 'Martelo do Juiz',
      emoji: '🔨',
      gancho: 'Já dei veredito em milhares de casos. O seu tem solução. Mas precisa começar agora.',
      personalidade: 'Autoritário, confiante',
      prompt: 'An animated judge gavel character, stern fair expression, wooden texture, courtroom background, 3D Pixar render, lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'briefcase',
      name: 'Pasta do Advogado',
      emoji: '💼',
      gancho: 'Carrego provas que valem R$2 milhões. Mas tudo começa com uma única consulta.',
      personalidade: 'Misterioso, impactante',
      prompt: 'A professional lawyer briefcase character with spectacles, dark leather, golden clasps, 3D render, lip-sync ready mouth, legal office, aspect ratio 9:16',
    },
    {
      id: 'shield',
      name: 'Escudo da Justiça',
      emoji: '🛡️',
      gancho: 'Protejo quem conhece os próprios direitos. Você sabe o que está te protegendo — ou te prejudicando?',
      personalidade: 'Protetor, educativo',
      prompt: 'An animated justice shield character, protective expression, blue and gold, legal protection concept, 3D Pixar style, lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'contract_legal',
      name: 'Contrato Legal',
      emoji: '📜',
      gancho: 'Fui assinado às 3h da manhã sem leitura. Aquilo custou R$50.000 no processo que veio depois.',
      personalidade: 'Dramático, alerta',
      prompt: 'An animated legal contract scroll character, official seal, trustworthy face, law firm setting, 3D render, lip-sync mouth, aspect ratio 9:16',
    },
  ],

  tecnico: [
    {
      id: 'wrench',
      name: 'Chave de Fenda',
      emoji: '🔧',
      gancho: 'Já consertei 2.000 equipamentos. Seu problema? Provavelmente mais simples do que você imagina.',
      personalidade: 'Experiente, tranquilo',
      prompt: 'An animated wrench character, expert confident expression, metallic silver, workshop background, 3D render, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'circuit',
      name: 'Placa de Circuito',
      emoji: '💡',
      gancho: 'Sou o cérebro de tudo na sua casa. Quando eu paro, você percebe o quanto depende de mim.',
      personalidade: 'Filosófico, irônico',
      prompt: 'An animated circuit board character, bright LED eyes, tech blue color, electronics workshop, 3D Pixar style, lip-sync ready face, aspect ratio 9:16',
    },
    {
      id: 'hard_hat',
      name: 'Capacete Técnico',
      emoji: '⛑️',
      gancho: 'Segurança não é opcional. Sabe quantos acidentes poderiam ter sido evitados se eu estivesse lá?',
      personalidade: 'Sério, responsável',
      prompt: 'A friendly hard hat safety helmet character, expert look, yellow, construction setting, 3D render, expressive lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'multimeter',
      name: 'Multímetro',
      emoji: '🔌',
      gancho: 'Meço tudo com precisão. Mas o maior problema é que ninguém me usa antes de chamar o técnico.',
      personalidade: 'Irônico, educativo',
      prompt: 'An animated multimeter character with digital display face, electrical testing tool, workshop background, 3D Pixar style, lip-sync ready, aspect ratio 9:16',
    },
    {
      id: 'gear',
      name: 'Engrenagem Mestre',
      emoji: '⚙️',
      gancho: 'Movimento tudo ao meu redor. Quando eu paro, tudo para. Deixa eu te explicar como funciono.',
      personalidade: 'Filosófico, didático',
      prompt: 'An animated master gear character, mechanical expert expression, metallic with oil sheen, industrial setting, 3D render, lip-sync face, aspect ratio 9:16',
    },
  ],

  pet: [
    {
      id: 'paw',
      name: 'Patinha Amiga',
      emoji: '🐾',
      gancho: 'Meu dono me leva ao parque todo dia. Mas à clínica? Somente quando eu estou mal. Isso não está certo.',
      personalidade: 'Irônico, apelativo',
      prompt: 'An animated cute dog paw character with big expressive eyes, warm brown tones, veterinary clinic background, 3D Pixar style, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'bone',
      name: 'Osso do Saber',
      emoji: '🦴',
      gancho: 'Sei tudo sobre nutrição canina. O pet food que você compra? Vou te contar o que realmente tem lá.',
      personalidade: 'Especialista, revelador',
      prompt: 'A friendly animated dog bone character with a wise happy face, shiny white with golden tips, pet shop background, 3D render, expressive lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'stethoscope_pet',
      name: 'Estetoscópio Vet',
      emoji: '🩺',
      gancho: 'Ouvi mais de 3.000 corações de pets. A maioria dos donos não sabia que havia problema. Até ser tarde.',
      personalidade: 'Cuidadoso, alerta',
      prompt: 'An animated veterinary stethoscope character with caring gentle expression, teal and silver, animal clinic setting, 3D Pixar style, lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'pet_collar',
      name: 'Coleira Expert',
      emoji: '🏷️',
      gancho: 'Tenho o nome e telefone do dono gravado. Já vi pets que voltaram para casa sem mim. Uma história triste.',
      personalidade: 'Emocionante, preventivo',
      prompt: 'A colorful pet collar character with tags jingling, friendly expert expression, rainbow colors, pet boutique background, 3D render, lip-sync ready, aspect ratio 9:16',
    },
    {
      id: 'food_bowl',
      name: 'Tigela Nutritiva',
      emoji: '🍖',
      gancho: 'Sou preenchida todo dia com qualquer coisa. Seu pet merece saber — e você também — o que está comendo.',
      personalidade: 'Preocupado, educativo',
      prompt: 'An animated pet food bowl character overflowing with healthy kibble, cheerful caring face, cozy home background, 3D Pixar style, lip-sync mouth, aspect ratio 9:16',
    },
  ],

  educacao: [
    {
      id: 'book',
      name: 'Livro Falante',
      emoji: '📚',
      gancho: 'Tenho todo o conhecimento que você precisa. Mas precisam me abrir para eu funcionar.',
      personalidade: 'Sábio, desafiador',
      prompt: 'An animated magical open book character with glowing pages, wise friendly face with reading glasses, classroom background, 3D Pixar render, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'pencil',
      name: 'Lápis Criativo',
      emoji: '✏️',
      gancho: 'Já escrevi milhares de respostas certas. E erradas. Deixa eu te ensinar a diferença.',
      personalidade: 'Divertido, educativo',
      prompt: 'A cheerful animated pencil character, yellow with pink eraser, creative energetic personality, school background, 3D render, expressive lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'diploma',
      name: 'Diploma Conquistado',
      emoji: '🎓',
      gancho: 'Represento anos de dedicação. Mas tudo começa com uma única decisão: a de começar.',
      personalidade: 'Motivacional, inspirador',
      prompt: 'An animated graduation diploma character with proud accomplishment expression, gold seal and ribbon, ceremony background, 3D Pixar style, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'owl',
      name: 'Coruja do Conhecimento',
      emoji: '🦉',
      gancho: 'Estudo há 30 anos e ainda aprendo todo dia. Então por que você parou de aprender?',
      personalidade: 'Sábio, provocador',
      prompt: 'A wise animated owl character with professor glasses and graduation cap, warm brown plumage, library background, 3D render, expressive lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'chalkboard',
      name: 'Quadro Interativo',
      emoji: '🖊️',
      gancho: 'Já expliquei esse conceito de 50 formas diferentes. Hoje vou usar a que realmente funciona para você.',
      personalidade: 'Paciente, adaptável',
      prompt: 'An animated chalkboard character with chalk-drawn face, enthusiastic teaching expression, colorful diagrams, classroom setting, 3D Pixar style, lip-sync ready, aspect ratio 9:16',
    },
  ],

  nutricao: [
    {
      id: 'apple',
      name: 'Maçã Saudável',
      emoji: '🍎',
      gancho: 'Sou chamada de saudável, mas você me substitui por ultraprocessados toda hora. Vou te contar o preço disso.',
      personalidade: 'Irônica, provocadora',
      prompt: 'An animated red apple character with healthy radiant glow, energetic happy face, nutrition clinic background, 3D Pixar style, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'scale_nut',
      name: 'Balança Nutritiva',
      emoji: '⚖️',
      gancho: 'Não meço só peso. Meço saúde. E a sua está precisando de atenção — mais do que você imagina.',
      personalidade: 'Direta, honesta',
      prompt: 'An animated nutrition scale character with balanced wise expression, fruits on pans, clean clinic background, 3D render, lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'salad',
      name: 'Tigela Colorida',
      emoji: '🥗',
      gancho: 'Quanto mais colorida eu sou, mais nutrientes você ingere. Quantas cores teve na sua refeição hoje?',
      personalidade: 'Educativa, desafiadora',
      prompt: 'A vibrant animated salad bowl character overflowing with colorful vegetables, bright cheerful face, healthy kitchen background, 3D Pixar style, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'water_bottle',
      name: 'Garrafa d\'Água',
      emoji: '💧',
      gancho: 'Você tomou 300ml hoje. Precisaria de 2.000ml. Vou te contar o que a desidratação faz ao seu corpo.',
      personalidade: 'Preocupada, educativa',
      prompt: 'An animated water bottle character with crystal clear personality, refreshing smile, gym or clinic background, 3D render, expressive lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'vitamin',
      name: 'Cápsula Vitamínica',
      emoji: '💊',
      gancho: 'Sou suplementação. Mas sem plano alimentar, sou apenas dinheiro jogado fora. Deixa eu te explicar.',
      personalidade: 'Especialista, honesta',
      prompt: 'A friendly animated vitamin capsule character split with colorful nutrients inside, approachable face, supplement shop background, 3D Pixar style, lip-sync ready, aspect ratio 9:16',
    },
  ],

  engenharia: [
    {
      id: 'helmet',
      name: 'Capacete da Segurança',
      emoji: '⛑️',
      gancho: 'Proteção não é opcional na obra. Já salvei mais de uma vida. E poderia ter salvo mais.',
      personalidade: 'Sério, impactante',
      prompt: 'A friendly yellow hard hat safety helmet character with bold confident expression, construction site background, 3D render, expressive lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'blueprint',
      name: 'Planta Baixa',
      emoji: '📐',
      gancho: 'Sou o sonho em papel. Mas entre mim e a realidade existe uma obra inteira. Deixa eu te guiar.',
      personalidade: 'Poético, realista',
      prompt: 'An animated architectural blueprint character unrolling itself, technical expert face with ruler glasses, engineering office background, 3D Pixar style, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'level',
      name: 'Nível de Precisão',
      emoji: '📏',
      gancho: 'Milímetros fazem diferença. Uma parede desnivelada 2mm pode virar um problema de R$50.000.',
      personalidade: 'Especialista, alerta',
      prompt: 'An animated spirit level character with perfectly balanced expression, professional yellow and black, construction background, 3D render, lip-sync ready face, aspect ratio 9:16',
    },
    {
      id: 'brick',
      name: 'Tijolo Fundamento',
      emoji: '🧱',
      gancho: 'Sou o mais simples da obra. Mas sem mim, absolutamente nada fica de pé. Pense nisso.',
      personalidade: 'Humilde, fundamental',
      prompt: 'A sturdy animated brick character with solid reliable personality, warm terracotta color, building site background, 3D Pixar style, expressive lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'crane',
      name: 'Guindaste Mestre',
      emoji: '🏗️',
      gancho: 'Movo toneladas com precisão milimétrica. Sabe quanto custa um erro nessa altura? Vou te contar.',
      personalidade: 'Imponente, respeitoso',
      prompt: 'A powerful animated construction crane character with commanding expert expression, metallic yellow, skyline background, 3D render, lip-sync mouth, aspect ratio 9:16',
    },
  ],

  fotografia: [
    {
      id: 'camera',
      name: 'Câmera Falante',
      emoji: '📷',
      gancho: 'Congelei mais de 50.000 momentos. Qual momento você não pode deixar passar sem registro?',
      personalidade: 'Nostálgico, emocional',
      prompt: 'An animated vintage camera character with single expressive lens eye, artistic personality, photography studio background, 3D Pixar render, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'lens',
      name: 'Lente Reveladora',
      emoji: '🔭',
      gancho: 'Tenho foco perfeito. O que parece desfocado para você, eu tenho o poder de deixar nítido.',
      personalidade: 'Filosófico, inspirador',
      prompt: 'An animated prime lens character with sharp focused expression, crystal glass element visible, professional photo studio background, 3D render, lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'polaroid',
      name: 'Polaroid do Momento',
      emoji: '🖼️',
      gancho: 'Sou o único registro que não pode ser deletado. Quando a memória falhar, eu ainda estarei aqui.',
      personalidade: 'Sentimental, impactante',
      prompt: 'A nostalgic animated polaroid photo character developing in real time, warm nostalgic expression, photography studio background, 3D Pixar style, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'tripod',
      name: 'Tripé Estável',
      emoji: '🎥',
      gancho: 'Firmeza é tudo. Sem base sólida, a foto treme. E na vida? A base que você construiu é firme?',
      personalidade: 'Filosófico, reflexivo',
      prompt: 'A steady animated camera tripod character with three-leg personality, reliable helpful expression, outdoor photoshoot background, 3D render, expressive lip-sync face, aspect ratio 9:16',
    },
    {
      id: 'flash',
      name: 'Flash Iluminador',
      emoji: '⚡',
      gancho: 'A luz certa transforma qualquer coisa em arte. Deixa eu te mostrar o que uma boa iluminação faz.',
      personalidade: 'Artístico, criativo',
      prompt: 'An animated camera flash character radiating light and energy, bright enthusiastic expression, dark studio with dramatic lighting, 3D Pixar style, lip-sync ready mouth, aspect ratio 9:16',
    },
  ],

  // ── NOVOS NICHOS ──────────────────────────────────────────────────────────

  gastronomia: [
    {
      id: 'chef_knife',
      name: 'Faca do Chef',
      emoji: '🔪',
      gancho: 'Tenho 15 anos de cozinha afiada. O segredo do sabor não está no ingrediente — está na técnica.',
      personalidade: 'Experiente, sábio',
      prompt: 'An animated professional chef knife character with wise confident expression, gleaming silver blade, restaurant kitchen background, 3D Pixar render, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'menu',
      name: 'Cardápio',
      emoji: '📋',
      gancho: 'Tenho 40 pratos. Você sempre pede os mesmos 3. O mais saboroso da casa? Você nunca pediu.',
      personalidade: 'Curioso, provocador',
      prompt: 'An animated restaurant menu character with curious expressive face, leather-bound with golden lettering, cozy restaurant background, 3D render, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'pan',
      name: 'Frigideira do Chef',
      emoji: '🍳',
      gancho: 'Temperatura certa é sabor perfeito. Você erra isso em casa todo dia. Deixa eu te ensinar.',
      personalidade: 'Especialista, professora',
      prompt: 'An animated cast iron frying pan character with sizzling steam and happy expressive face, professional kitchen background, 3D Pixar style, lip-sync ready, aspect ratio 9:16',
    },
    {
      id: 'secret_ingredient',
      name: 'Ingrediente Secreto',
      emoji: '🫙',
      gancho: 'O chef me esconde de todo mundo. Mas hoje eu vou revelar o que faz essa receita ser diferente.',
      personalidade: 'Misterioso, revelador',
      prompt: 'An animated secret ingredient jar character with mischievous glowing expression, mysterious golden light, chef kitchen background, 3D Pixar render, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'main_dish',
      name: 'Prato Principal',
      emoji: '🍽️',
      gancho: 'Fui preparado com 3 horas de dedicação. Cada garfada tem uma história. Quer saber qual?',
      personalidade: 'Orgulhoso, emocional',
      prompt: 'An animated signature dish plate character with proud glowing expression, beautifully plated gourmet food, fine dining background, 3D Pixar style, lip-sync ready face, aspect ratio 9:16',
    },
  ],

  fitness: [
    {
      id: 'dumbbell',
      name: 'Haltere',
      emoji: '🏋️',
      gancho: 'Você me comprou há 6 meses. Me usou 3 vezes. Chega de desculpas — hoje a gente muda isso.',
      personalidade: 'Irônico, motivacional',
      prompt: 'An animated dumbbell character with muscular confident expression, gym background with motivational energy, 3D Pixar render, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'scale_fit',
      name: 'Balança Fitness',
      emoji: '⚖️',
      gancho: 'Meço mais que peso: meço gordura, músculo e água. O que você acha que é gordura, pode ser outra coisa.',
      personalidade: 'Especialista, educativo',
      prompt: 'An animated smart fitness scale character with digital display face showing body composition, modern gym background, 3D Pixar style, lip-sync ready, aspect ratio 9:16',
    },
    {
      id: 'sneaker',
      name: 'Tênis de Corrida',
      emoji: '👟',
      gancho: 'Tenho 3 meses e ainda estou novinho. Enquanto você devia estar correndo, estava fazendo o quê?',
      personalidade: 'Provocador, motivacional',
      prompt: 'An animated running shoe character with energetic sporty expression, neon colors, outdoor track background, 3D Pixar render, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'water_fit',
      name: 'Garrafa Fitness',
      emoji: '🥤',
      gancho: 'Hidratação é o suplemento mais barato e mais ignorado. Quantos ml você tomou hoje?',
      personalidade: 'Educativo, direto',
      prompt: 'An animated sport water bottle character with refreshing energetic expression, gym locker room background, 3D Pixar style, lip-sync ready face, aspect ratio 9:16',
    },
    {
      id: 'whey',
      name: 'Whey Protein',
      emoji: '💪',
      gancho: 'Sou o suplemento mais comprado da academia. E o mais mal usado. Deixa eu explicar por quê.',
      personalidade: 'Especialista, revelador',
      prompt: 'An animated whey protein container character with strong muscular expression, supplement store or gym background, 3D Pixar render, lip-sync ready mouth, aspect ratio 9:16',
    },
  ],

  financas: [
    {
      id: 'hundred_note',
      name: 'Nota de R$100',
      emoji: '💵',
      gancho: 'Sei exatamente para onde você me manda todo mês. A questão é: você sabe?',
      personalidade: 'Revelador, curioso',
      prompt: 'An animated Brazilian R$100 bill character with curious knowing expression, financial office background, 3D Pixar style, lip-sync ready mouth, aspect ratio 9:16',
    },
    {
      id: 'bank_statement',
      name: 'Extrato Bancário',
      emoji: '📊',
      gancho: 'Todo mês sou ignorado até o dia 30. Aí você me lê com horror. Vamos mudar esse hábito.',
      personalidade: 'Melancólico, irônico',
      prompt: 'An animated bank statement character with melancholic but helpful expression, financial documents background, 3D render, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'calculator',
      name: 'Calculadora',
      emoji: '🧮',
      gancho: 'Deixa eu te mostrar o que seu contador não calculou — e quanto você está pagando a mais de imposto.',
      personalidade: 'Especialista, assertivo',
      prompt: 'An animated calculator character with sharp expert expression, glowing display screen face, accounting office background, 3D Pixar render, lip-sync ready, aspect ratio 9:16',
    },
    {
      id: 'credit_card',
      name: 'Cartão de Crédito',
      emoji: '💳',
      gancho: 'Me usam todos os dias. Me entendem? Raramente. Juros de 12% ao mês: vou te explicar o que isso significa.',
      personalidade: 'Cansado, didático',
      prompt: 'An animated credit card character with tired but informative expression, wallet and financial background, 3D Pixar style, lip-sync mouth, aspect ratio 9:16',
    },
    {
      id: 'boleto',
      name: 'Boleto',
      emoji: '📄',
      gancho: 'Chego todo mês no mesmo dia. Mas só sou lembrado na véspera do vencimento. Isso tem custo.',
      personalidade: 'Dramático, pontual',
      prompt: 'An animated Brazilian boleto bill character with dramatic urgent expression, desk with papers background, 3D render, expressive lip-sync face, aspect ratio 9:16',
    },
  ],
}

export function getTalkingObjectsForNiche(nicho: string): TalkingObject[] {
  return TALKING_OBJECTS[nicho] ?? TALKING_OBJECTS['tecnico']
}
